-- MySQL Script generated by MySQL Workbench
-- Sun Sep 21 11:37:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ENTREGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENTREGA` (
  `idENTREGA` INT NOT NULL,
  `ID_PEDIDO` INT NOT NULL,
  `STATUS_ENTREGA` VARCHAR(45) NULL,
  `CODIGO_RASTREIO` VARCHAR(45) NULL,
  PRIMARY KEY (`idENTREGA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `idPEDIDO` INT NOT NULL,
  `ID_CLIENTE` INT NOT NULL,
  `DATA_PEDIDO` DATE NULL,
  `ENTREGA_idENTREGA` INT NOT NULL,
  PRIMARY KEY (`idPEDIDO`, `ENTREGA_idENTREGA`),
  INDEX `fk_PEDIDO_ENTREGA1_idx` (`ENTREGA_idENTREGA` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_ENTREGA1`
    FOREIGN KEY (`ENTREGA_idENTREGA`)
    REFERENCES `mydb`.`ENTREGA` (`idENTREGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `ENDEREÇO` VARCHAR(255) NULL,
  `CONTATO` VARCHAR(45) NULL,
  `PEDIDO_idPEDIDO` INT NOT NULL,
  `PEDIDO_ENTREGA_idENTREGA` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE`),
  INDEX `fk_CLIENTE_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC, `PEDIDO_ENTREGA_idENTREGA` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO` , `PEDIDO_ENTREGA_idENTREGA`)
    REFERENCES `mydb`.`PEDIDO` (`idPEDIDO` , `ENTREGA_idENTREGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE PJ` (
  `idCLIENTE PJ` INT NOT NULL,
  `CNPJ` VARCHAR(14) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE PJ`, `CLIENTE_idCLIENTE`),
  INDEX `fk_CLIENTE PJ_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE PJ_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE PF` (
  `idCLIENTE PF` INT NOT NULL,
  `CPF` VARCHAR(11) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE PF`, `CLIENTE_idCLIENTE`),
  INDEX `fk_CLIENTE PF_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE PF_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGAMENTO` (
  `idPAGAMENTO` INT NOT NULL,
  `TIPO_PAGAMENTO` VARCHAR(45) NOT NULL,
  `VALOR` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idPAGAMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO_has_PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO_has_PAGAMENTO` (
  `PEDIDO_idPEDIDO` INT NOT NULL,
  `PAGAMENTO_idPAGAMENTO` INT NOT NULL,
  PRIMARY KEY (`PEDIDO_idPEDIDO`, `PAGAMENTO_idPAGAMENTO`),
  INDEX `fk_PEDIDO_has_PAGAMENTO_PAGAMENTO1_idx` (`PAGAMENTO_idPAGAMENTO` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PAGAMENTO_PEDIDO_idx` (`PEDIDO_idPEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_PAGAMENTO_PEDIDO`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `mydb`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PAGAMENTO_PAGAMENTO1`
    FOREIGN KEY (`PAGAMENTO_idPAGAMENTO`)
    REFERENCES `mydb`.`PAGAMENTO` (`idPAGAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
